name: CI/CD - .NET 9 + Docker

on:
  push:
    branches:
      - main

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      # 1. Checkout del código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup .NET 9
      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      # 3. Restore NuGet packages
      - name: Restore dependencies
        run: dotnet restore Asisya.ProductsApi.sln

      # 4. Build solution
      - name: Build solution
        run: dotnet build Asisya.ProductsApi.sln -c Release --no-restore

      # 5. Run tests
      - name: Run tests
        run: dotnet test Asisya.ProductsApi.sln --no-restore --verbosity normal

      # 6. Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 7. Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/asisya-products-api:latest -f Dockerfile .

      # 8. Push Docker image
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/asisya-products-api:latest
